"""내곁의 여비 웹 페이지 문구(5개 언어)."""

LANGS = ['ko', 'en', 'ja', 'zh-hans', 'zh-hant']
HTML_LANG = {'ko': 'ko', 'en': 'en', 'ja': 'ja', 'zh-hans': 'zh-Hans', 'zh-hant': 'zh-Hant'}
LANG_NAME = {'ko': '한국어', 'en': 'English', 'ja': '日本語', 'zh-hans': '简体中文', 'zh-hant': '繁體中文'}
EMAIL = 'ekqlszzzz@naver.com'

APP = {
    'ko': '내곁의 여비',
    'en': 'BySide Trip',
    'ja': 'BySide 旅行',
    'zh-hans': 'BySide 旅行',
    'zh-hant': 'BySide 旅行',
}

# 소개 페이지 ---------------------------------------------------------------
INTRO = {
    'ko': {
        'title': '내곁의 여비 · 여행 환율 계산기와 여행 가계부',
        'desc': '여행지 돈을 원화로 바로 계산하고, 쓴 돈을 한 번에 기록하는 여행 가계부. 인터넷이 없어도 돼요.',
        'nav': ('화면', '기능', '고객 지원'),
        'h1': '여행지 돈,<br><em>바로</em> 원화로',
        'lead': '환율 계산부터 여행 가계부까지.<br>인터넷이 없어도 한 앱으로 끝내요.',
        'chips': ['1:1 환율 계산', '한 번에 지출 기록', '오프라인', '홈 화면 위젯'],
        'store': ('App Store 출시 준비 중', 'Google Play 출시 준비 중'),
        'screens_h': '이렇게 생겼어요',
        'screens_sub': '옆으로 넘겨 보세요.',
        'shots': [
            ('01-convert', '여행지 통화와 원화를 1:1로 나란히 계산하는 여행 화면'),
            ('02-record', '금액을 분류·결제 수단·메모와 함께 기록하는 지출 기록 창'),
            ('03-expenses', '여행 합계, 남은 현금, 날짜별 지출을 보여 주는 지출 화면'),
            ('04-rates', '여러 통화를 한 번에 비교하는 환율 화면'),
            ('05-widget', '이번 여행·오늘 쓴 돈·환율을 보여 주는 홈 화면 위젯'),
        ],
        'feat_h': '여행에 필요한 것만',
        'feat_sub': '계산하고, 기록하고, 확인하는 것까지 한 앱에서요.',
        'features': [
            ('1:1 환율 계산', '여행지를 고르면 그 나라 돈과 원화가 나란히. 사칙연산도 돼요.'),
            ('한 번에 지출 기록', '계산한 금액을 식비·교통·쇼핑 같은 분류와 메모로 바로 남겨요.'),
            ('남은 현금까지', '현금과 카드를 나눠 보고, 환전한 돈에서 남은 현금을 알려 줘요.'),
            ('인터넷이 없어도', '환율을 기기에 저장해 두고, 앱에도 들어 있어 처음부터 바로 돼요.'),
            ('홈·잠금 화면 위젯', '여행 위젯과 환율 위젯. 보여 줄 통화와 배경색을 골라요.'),
            ('166개 통화 · 5개 언어', '한국어·영어·일본어·중국어(간체·번체), 다크 모드 지원.'),
        ],
        'promise_h': '내 기록은 내 폰에만',
        'promise': [
            '회원가입이 없어요. 지출 기록은 서버로 보내지 않고 폰에만 저장해요.',
            '폰을 바꿀 때는 백업 파일 하나로 그대로 옮기고, 엑셀(CSV)로도 내보낼 수 있어요.',
        ],
        'note': '시장 기준 환율이에요. 은행·카드 환율과 수수료는 다를 수 있어요.',
        'footer': ('고객 지원', '개인정보처리방침', '문의'),
    },
    'en': {
        'title': 'BySide Trip · Travel currency converter and trip expense log',
        'desc': 'Convert travel prices side by side with your own currency and log spending in one tap. Works offline.',
        'nav': ('Screens', 'Features', 'Support'),
        'h1': 'Travel money,<br>in <em>your</em> currency',
        'lead': 'From currency conversion to a trip expense log,<br>all in one app that works offline.',
        'chips': ['Side-by-side conversion', 'One-tap expense log', 'Offline', 'Widgets'],
        'store': ('Coming soon to the App Store', 'Coming soon to Google Play'),
        'screens_h': 'Take a look',
        'screens_sub': 'Swipe to see more.',
        'shots': [
            ('01-convert', 'Trip screen converting the local currency and your currency side by side'),
            ('02-record', 'Logging an expense with a category, payment method and note'),
            ('03-expenses', 'Expenses screen with the trip total, cash left and daily spending'),
            ('04-rates', 'Rates screen comparing many currencies at once'),
        ],
        'feat_h': 'Just what a trip needs',
        'feat_sub': 'Convert, log and check, all in one app.',
        'features': [
            ('Side-by-side conversion', 'Pick a destination and its currency sits next to yours. The keypad does math too.'),
            ('One-tap expense log', 'Save an amount with a category such as Food or Transport, plus a note.'),
            ('Cash left, too', 'See cash and card separately, and how much exchanged cash is left.'),
            ('Works offline', 'Rates are saved on the device and built into the app, so it works from the first launch.'),
            ('Home and Lock Screen widgets', 'A trip widget and a rates widget. Choose currencies and background colors.'),
            ('166 currencies · 5 languages', 'English, Korean, Japanese and Chinese (Simplified and Traditional), with dark mode.'),
        ],
        'promise_h': 'Your records stay on your phone',
        'promise': [
            'No account. Expenses are never sent to a server; they stay on your phone.',
            'Move to a new phone with a single backup file, or export a CSV for spreadsheets.',
        ],
        'note': 'Rates are mid-market reference rates. Bank and card rates and fees may differ.',
        'footer': ('Support', 'Privacy Policy', 'Contact'),
    },
    'ja': {
        'title': 'BySide 旅行 · 旅行用の為替換算と旅の家計簿',
        'desc': '旅先の値段を自分の通貨ですぐ換算し、使ったお金をワンタップで記録。オフラインでも使えます。',
        'nav': ('画面', '機能', 'サポート'),
        'h1': '旅先のお金を、<br><em>すぐ</em>自分の通貨で',
        'lead': '為替換算から旅の家計簿まで。<br>オフラインでもひとつのアプリで。',
        'chips': ['並べて換算', 'ワンタップで記録', 'オフライン', 'ウィジェット'],
        'store': ('App Store 近日公開', 'Google Play 近日公開'),
        'screens_h': 'アプリの画面',
        'screens_sub': '横にスワイプしてご覧ください。',
        'shots': [
            ('01-convert', '旅先の通貨と自分の通貨を並べて換算する旅行画面'),
            ('02-record', '分類・支払い方法・メモと一緒に支出を記録する画面'),
            ('03-expenses', '旅行の合計、残りの現金、日付ごとの支出を表示する支出画面'),
            ('04-rates', '複数の通貨をまとめて比べる為替画面'),
        ],
        'feat_h': '旅に必要なものだけ',
        'feat_sub': '換算、記録、確認までひとつのアプリで。',
        'features': [
            ('並べて換算', '行き先を選ぶと、現地の通貨と自分の通貨が並んで表示。四則演算もできます。'),
            ('ワンタップで記録', '換算した金額を、食費・交通などの分類とメモを付けてすぐ保存。'),
            ('残りの現金まで', '現金とカードを分けて表示し、両替したお金の残りもわかります。'),
            ('オフラインでも', 'レートを端末に保存し、アプリにも内蔵。初めての起動からすぐ使えます。'),
            ('ホーム・ロック画面ウィジェット', '旅行ウィジェットとレートウィジェット。通貨と背景色を選べます。'),
            ('166通貨・5言語', '日本語・英語・韓国語・中国語（簡体字・繁体字）、ダークモード対応。'),
        ],
        'promise_h': '記録はあなたのスマートフォンだけに',
        'promise': [
            'アカウント登録は不要です。支出の記録はサーバーに送らず、端末にだけ保存します。',
            '機種変更はバックアップファイルひとつで。CSV にも書き出せます。',
        ],
        'note': '市場の参考レートです。銀行やカードのレート・手数料とは異なる場合があります。',
        'footer': ('サポート', 'プライバシーポリシー', 'お問い合わせ'),
    },
    'zh-hans': {
        'title': 'BySide 旅行 · 旅行汇率换算与旅行记账',
        'desc': '旅行地的价格马上换算成你的货币，花的钱一键记下。没有网络也能用。',
        'nav': ('界面', '功能', '客户支持'),
        'h1': '旅行地的钱，<br><em>马上</em>换算',
        'lead': '从汇率换算到旅行记账，<br>没有网络也能用一个应用搞定。',
        'chips': ['并排换算', '一键记账', '离线可用', '小组件'],
        'store': ('即将登陆 App Store', '即将登陆 Google Play'),
        'screens_h': '应用界面',
        'screens_sub': '左右滑动查看。',
        'shots': [
            ('01-convert', '当地货币与你的货币并排换算的旅行页面'),
            ('02-record', '带分类、支付方式和备注记录支出的页面'),
            ('03-expenses', '显示旅行合计、剩余现金和每日支出的支出页面'),
            ('04-rates', '同时比较多种货币的汇率页面'),
        ],
        'feat_h': '旅行需要的，刚刚好',
        'feat_sub': '换算、记账、查看，一个应用全搞定。',
        'features': [
            ('并排换算', '选好目的地，当地货币和你的货币并排显示，还能加减乘除。'),
            ('一键记账', '换算好的金额直接加上餐饮、交通等分类和备注保存。'),
            ('剩余现金一目了然', '现金和刷卡分开显示，兑换的现金还剩多少也能看到。'),
            ('没有网络也能用', '汇率保存在设备上，应用也自带汇率，首次打开就能用。'),
            ('主屏幕和锁定屏幕小组件', '旅行小组件和汇率小组件，可自选货币和背景颜色。'),
            ('166 种货币 · 5 种语言', '简体中文、繁体中文、英语、韩语、日语，支持深色模式。'),
        ],
        'promise_h': '记录只保存在你的手机上',
        'promise': [
            '无需注册账号。支出记录不会发送到服务器，只保存在手机上。',
            '换手机时用一个备份文件就能迁移，也可以导出为 CSV。',
        ],
        'note': '显示的是市场参考汇率，可能与银行、信用卡的汇率和手续费不同。',
        'footer': ('客户支持', '隐私政策', '联系我们'),
    },
    'zh-hant': {
        'title': 'BySide 旅行 · 旅遊匯率換算與旅行記帳',
        'desc': '旅遊地的價格馬上換算成你的貨幣，花的錢點一下就記下。沒有網路也能用。',
        'nav': ('畫面', '功能', '客戶支援'),
        'h1': '旅遊地的錢，<br><em>馬上</em>換算',
        'lead': '從匯率換算到旅行記帳，<br>沒有網路也能用一個 App 搞定。',
        'chips': ['並排換算', '一鍵記帳', '離線可用', '小工具'],
        'store': ('即將登上 App Store', '即將登上 Google Play'),
        'screens_h': 'App 畫面',
        'screens_sub': '左右滑動查看。',
        'shots': [
            ('01-convert', '當地貨幣與你的貨幣並排換算的旅行頁面'),
            ('02-record', '加上分類、付款方式和備註記錄支出的頁面'),
            ('03-expenses', '顯示旅行合計、剩餘現金和每日支出的支出頁面'),
            ('04-rates', '同時比較多種貨幣的匯率頁面'),
        ],
        'feat_h': '旅行需要的，剛剛好',
        'feat_sub': '換算、記帳、查看，一個 App 全搞定。',
        'features': [
            ('並排換算', '選好目的地，當地貨幣和你的貨幣並排顯示，還能加減乘除。'),
            ('一鍵記帳', '換算好的金額直接加上餐飲、交通等分類和備註儲存。'),
            ('剩餘現金一目了然', '現金和刷卡分開顯示，換匯的現金還剩多少也看得到。'),
            ('沒有網路也能用', '匯率儲存在裝置上，App 也內建匯率，第一次打開就能用。'),
            ('主畫面與鎖定畫面小工具', '旅行小工具和匯率小工具，可自選貨幣和背景顏色。'),
            ('166 種貨幣 · 5 種語言', '繁體中文、簡體中文、英文、韓文、日文，支援深色模式。'),
        ],
        'promise_h': '記錄只存在你的手機裡',
        'promise': [
            '不用註冊帳號。支出記錄不會傳到伺服器，只儲存在手機上。',
            '換手機時用一個備份檔就能搬移，也可以匯出成 CSV。',
        ],
        'note': '顯示的是市場參考匯率，可能與銀行、信用卡的匯率和手續費不同。',
        'footer': ('客戶支援', '隱私權政策', '聯絡我們'),
    },
}
